apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
    spec:
      containers:
        - livenessProbe:
            httpGet:
              path: /health/live
          readinessProbe:
            httpGet:
              path: /health/ready
  traffic:
